SCRIPT_PATH: /home/kruu/git_folder/wake_encounter/run/run_sim.sh
APP_ROOT: /home/kruu/git_folder/wake_encounter
Sourcing /cm/shared/apps/Miniforge3/etc/profile.d/conda.sh
Sourcing /cm/shared/apps/Miniforge3/etc/profile.d/mamba.sh
Sourcing /cm/shared/apps/Miniforge3/etc/profile.d/conda.sh
Sourcing /cm/shared/apps/Miniforge3/etc/profile.d/mamba.sh
I am running on srv-lab-t-250
I am running with job id 5037
Traceback (most recent call last):
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 134, in <module>
    main()
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 121, in main
    fuselage_wing_config.run()
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fuselage_wing_configuration.py", line 70, in run
    sharpy.sharpy_main.main(['', self.case_route + '/' + self.case_name + '.sharpy'])  
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 167, in main
    raise e
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 142, in main
    data = solvers[solver_name].run(solvers=solvers)
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/dynamicuvlm.py", line 141, in run
    self.data = self.aero_solver.run(aero_tstep=aero_tstep,
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/stepuvlm.py", line 227, in run
    self.velocity_generator.generate({'zeta': aero_tstep.zeta,
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 266, in generate
    self.update_cache(t)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 318, in update_cache
    self._interpolator1 = self.read_grid(self._it1, i_cache=1)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 453, in read_grid
    file_name = self.grid_data['grid'][i_grid][velocities[i_dim]]['file']
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 134, in <module>
    main()
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 121, in main
    fuselage_wing_config.run()
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fuselage_wing_configuration.py", line 70, in run
    sharpy.sharpy_main.main(['', self.case_route + '/' + self.case_name + '.sharpy'])  
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 167, in main
    raise e
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 142, in main
    data = solvers[solver_name].run(solvers=solvers)
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/dynamicuvlm.py", line 141, in run
    self.data = self.aero_solver.run(aero_tstep=aero_tstep,
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/stepuvlm.py", line 227, in run
    self.velocity_generator.generate({'zeta': aero_tstep.zeta,
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 266, in generate
    self.update_cache(t)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 314, in update_cache
    self._interpolator0 = self.read_grid(self._it0, i_cache=0)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 453, in read_grid
    file_name = self.grid_data['grid'][i_grid][velocities[i_dim]]['file']
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 134, in <module>
    main()
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 121, in main
    fuselage_wing_config.run()
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fuselage_wing_configuration.py", line 70, in run
    sharpy.sharpy_main.main(['', self.case_route + '/' + self.case_name + '.sharpy'])  
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 167, in main
    raise e
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 142, in main
    data = solvers[solver_name].run(solvers=solvers)
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/dynamicuvlm.py", line 141, in run
    self.data = self.aero_solver.run(aero_tstep=aero_tstep,
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/stepuvlm.py", line 227, in run
    self.velocity_generator.generate({'zeta': aero_tstep.zeta,
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 266, in generate
    self.update_cache(t)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 318, in update_cache
    self._interpolator1 = self.read_grid(self._it1, i_cache=1)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 453, in read_grid
    file_name = self.grid_data['grid'][i_grid][velocities[i_dim]]['file']
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 134, in <module>
    main()
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 121, in main
    fuselage_wing_config.run()
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fuselage_wing_configuration.py", line 70, in run
    sharpy.sharpy_main.main(['', self.case_route + '/' + self.case_name + '.sharpy'])  
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 167, in main
    raise e
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 142, in main
    data = solvers[solver_name].run(solvers=solvers)
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/dynamicuvlm.py", line 141, in run
    self.data = self.aero_solver.run(aero_tstep=aero_tstep,
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/stepuvlm.py", line 227, in run
    self.velocity_generator.generate({'zeta': aero_tstep.zeta,
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 266, in generate
    self.update_cache(t)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 318, in update_cache
    self._interpolator1 = self.read_grid(self._it1, i_cache=1)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 453, in read_grid
    file_name = self.grid_data['grid'][i_grid][velocities[i_dim]]['file']
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 134, in <module>
    main()
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 121, in main
    fuselage_wing_config.run()
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fuselage_wing_configuration.py", line 70, in run
    sharpy.sharpy_main.main(['', self.case_route + '/' + self.case_name + '.sharpy'])  
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 167, in main
    raise e
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 142, in main
    data = solvers[solver_name].run(solvers=solvers)
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/dynamicuvlm.py", line 141, in run
    self.data = self.aero_solver.run(aero_tstep=aero_tstep,
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/stepuvlm.py", line 227, in run
    self.velocity_generator.generate({'zeta': aero_tstep.zeta,
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 266, in generate
    self.update_cache(t)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 318, in update_cache
    self._interpolator1 = self.read_grid(self._it1, i_cache=1)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 453, in read_grid
    file_name = self.grid_data['grid'][i_grid][velocities[i_dim]]['file']
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 134, in <module>
    main()
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 121, in main
    fuselage_wing_config.run()
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fuselage_wing_configuration.py", line 70, in run
    sharpy.sharpy_main.main(['', self.case_route + '/' + self.case_name + '.sharpy'])  
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 167, in main
    raise e
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 142, in main
    data = solvers[solver_name].run(solvers=solvers)
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/dynamicuvlm.py", line 141, in run
    self.data = self.aero_solver.run(aero_tstep=aero_tstep,
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/stepuvlm.py", line 227, in run
    self.velocity_generator.generate({'zeta': aero_tstep.zeta,
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 266, in generate
    self.update_cache(t)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 314, in update_cache
    self._interpolator0 = self.read_grid(self._it0, i_cache=0)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 453, in read_grid
    file_name = self.grid_data['grid'][i_grid][velocities[i_dim]]['file']
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 134, in <module>
    main()
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kruu/.conda/envs/wake_encounter/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fwc_wake_encounter.py", line 121, in main
    fuselage_wing_config.run()
  File "/home/kruu/git_folder/wake_encounter/wake_modeling/fuselage_wing_configuration.py", line 70, in run
    sharpy.sharpy_main.main(['', self.case_route + '/' + self.case_name + '.sharpy'])  
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 167, in main
    raise e
  File "/home/kruu/git_folder/sharpy/sharpy/sharpy_main.py", line 142, in main
    data = solvers[solver_name].run(solvers=solvers)
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/dynamicuvlm.py", line 141, in run
    self.data = self.aero_solver.run(aero_tstep=aero_tstep,
  File "/home/kruu/git_folder/sharpy/sharpy/solvers/stepuvlm.py", line 227, in run
    self.velocity_generator.generate({'zeta': aero_tstep.zeta,
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 266, in generate
    self.update_cache(t)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 318, in update_cache
    self._interpolator1 = self.read_grid(self._it1, i_cache=1)
  File "/home/kruu/git_folder/sharpy/sharpy/generators/turbvelocityfield.py", line 453, in read_grid
    file_name = self.grid_data['grid'][i_grid][velocities[i_dim]]['file']
IndexError: list index out of range
